---
title: "xiphoid cartilage"
output: github_document
---

```{r bodyclocks_setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
source(file.path("..", "R", "io_utils.R"))
source(file.path("..", "R", "annotation_utils.R"))
source(file.path("..", "R", "biomart_utils.R"))
source(file.path("..", "R", "string_utils.R"))
source(file.path("..", "R", "validation_utils.R"))
ensure_dir(file.path("..", "results", "tables"))
ensure_dir(file.path("..", "results", "reports"))
ensure_dir(file.path("..", "results", "shiny_data", "mouse"))
ensure_dir(file.path("..", "results", "shiny_data", "baboon"))
```


## Load libraries

```{r libraries, message=FALSE}
library(AnnotationDbi)
library(mouse4302.db)
library(dplyr)
library(tidyr)
library(rain)
library(genefilter)
library(httr)
library(jsonlite)
library(STRINGdb)
```

## Load data

```{r load_data}
dat <- read.csv("data/raw/xiphoid_array.csv", row.names = 1)

# Remove unannotated genes denoted by "---" in Gene.Name column
dat <- dat[dat$Gene.Name != "---", ]
```


## Collapse duplicate probes (keep highest mean expression per gene)

```{r collapse_duplicates}
dat$mean_expr <- rowMeans(dat[, !colnames(dat) %in% "Gene.Name"])

dat <- dat[order(dat$Gene.Name, -dat$mean_expr), ]
dat <- dat[!duplicated(dat$Gene.Name), ]

# Remove rows that have no Gene.Name NA or empty
dat <- dat[!is.na(dat$Gene.Name) & dat$Gene.Name != "", ]

rownames(dat) <- dat$Gene.Name
dat$Gene.Name <- NULL
dat$mean_expr   <- NULL

dim(dat)
```

## Filter genes without Ensembl IDs

```{r filter_no_ensembl}
ensembl_ids <- mapIds(
  mouse4302.db,
  keys      = rownames(dat),
  column    = "ENSEMBL",
  keytype   = "SYMBOL",
  multiVals = "first"
)

dat <- dat[!is.na(ensembl_ids), ]


dim(dat)
```

```{r run_rain}
RAIN <- rain(t(dat), deltat=4, period=24, nr.series = 1,
                peak.border=c(0.3, 0.7), method = "independent", adjp.method='ABH', verbose=TRUE) # independent for mouse sampling, longitudinal can be used for cell culture

p_values <- RAIN$pVal

RAIN$BH.Q <- p.adjust(p_values, method = "BH")

# Adjust phase: first sample is ZT3, not ZT0
RAIN$phase <- (RAIN$phase + 3) %% 24

merged <- merge(dat, RAIN, by = "row.names")
rownames(merged) <- merged$Row.names
```


```{r add_descriptions}
merged$description <- mapIds(
  mouse4302.db,
  keys      = merged$Row.names,
  column    = "GENENAME",
  keytype   = "SYMBOL",
  multiVals = "first"
)

merged$ENSEMBL <- mapIds(
  mouse4302.db,
  keys      = merged$Row.names,
  column    = "ENSEMBL",
  keytype   = "SYMBOL",
  multiVals = "first"
)

gene_info <- data.frame(
  symbol = merged$Row.names,
  preferred_symbol = merged$Row.names,
  description = merged$description,
  ENSEMBL = merged$ENSEMBL,
  stringsAsFactors = FALSE
)

merged$preferred_symbol <- merged$Row.names

write.csv(merged, "results/tables/xiphoid_cartilage_circ.csv", row.names = FALSE)
```



```{r prepare_string_nodes}
# Get STRING DB interaction data and functional enrichment

nodes_data <- merged %>%
    filter(BH.Q <= 0.05) %>%
    dplyr::rename(symbol = preferred_symbol)

# ENSEMBL gene IDs return more results than MGI symbols
gene_list <- nodes_data$ENSEMBL
enrichment_background_genes <- unique(stats::na.omit(merged$ENSEMBL))

gene_mapping <- create_gene_mapping(
  gene_ids = merged$ENSEMBL,
  symbols = nodes_data$symbol
)

cat("Created mapping for", length(gene_mapping), "genes\n")
```

```{r build_string_network}
# Get protein-protein interactions and enrichment data using STRINGdb

enrichment_backgrounds <- get_string_enrichment_backgrounds(
  foreground_genes = gene_list,
  tested_genes = enrichment_background_genes,
  species_id = 10090
)

network_bundle <- get_string_network_bundle(
  gene_list = gene_list,
  gene_mapping = gene_mapping,
  species_id = 10090,
  nodes_data = nodes_data,
  id_col = "ENSEMBL",
  include_enrichment = FALSE
)
edges <- network_bundle$edges_by_threshold
cluster_data <- enrichment_backgrounds$backgrounds$all_string$cluster_data


phase_colors <- c("3" = "orange", "7" = "yellow", "11" = "red", "15" = "purple", "19" = "navy", "23" = "lightblue")

network_outputs <- build_string_network_outputs(
  cluster_data = cluster_data,
  nodes_data = nodes_data,
  gene_info = gene_info,
  gene_mapping = gene_mapping,
  phase_colors = phase_colors)
enrichment_background_bundle <- build_string_enrichment_background_bundle(
  enrichment_backgrounds, nodes_data, gene_info, gene_mapping, phase_colors
)

cluster_data <- network_outputs$cluster_data
nodes <- network_outputs$nodes
nodes_with_tooltips <- network_outputs$nodes_with_tooltips
cluster_for_plot <- network_outputs$cluster_for_plot
cluster_descriptions <- network_outputs$cluster_descriptions

save_string_network_outputs(
  outputs = network_outputs,
  edges = edges,
  output_dir = "results/shiny_data/mouse/xiphoid_cartilage",
  prefix = "xiphoid"
)
save_string_enrichment_background_bundle(
  enrichment_background_bundle,
  output_dir = "results/shiny_data/mouse/xiphoid_cartilage",
  prefix = "xiphoid"
)
```


```{r prepare_timeseries_data}
plotting <- merged[, c("Row.names", "X0", "X4", "X8", "X12", "X16", "X20", "X24", "X28", "X32", "X36", "X40")]
new_col_names <- c("Gene", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11")
colnames(plotting) <- new_col_names

qval_df <- merged[c("Row.names", "BH.Q")]
new_qval_names <- c("Gene", "BH.Q")
colnames(qval_df) <- new_qval_names

plotting2 <- pivot_longer(plotting, cols = !Gene, names_to = "time_point", values_to = "mean")
plotting2 <- inner_join(plotting2, qval_df, by = "Gene")


save_rds_checked(plotting2, file = "results/shiny_data/mouse/xiphoid_cartilage/xiphoid_data.rds")

```



```{r compute_amplitude_display_table}
# Process data frame for plotting in bodyclocks shiny app
dt <- merged

dt <- dt %>%
  dplyr::mutate(ZT3 = rowMeans(dplyr::select(., c("X0", "X24"))),
         ZT7 = rowMeans(dplyr::select(., c("X4", "X28"))),
         ZT11 = rowMeans(dplyr::select(., c("X8", "X32"))),
         ZT15 = rowMeans(dplyr::select(., c("X12", "X36"))),
         ZT19 = rowMeans(dplyr::select(., c("X16", "X40"))),
         ZT23 = X20
  )


means <- dt[c("ZT3", "ZT7", "ZT11", "ZT15", "ZT19", "ZT23")]

min_val <- apply(means, 1, min)
max_val <- apply(means, 1, max)




Amp_fc_log2 <- log2(max_val / min_val)
Amp_fc <- max_val / min_val


dt <- cbind(dt, Amp_fc_log2, Amp_fc)

display_dt <- dt %>%
  dplyr::select(preferred_symbol, description, pVal, BH.Q, Amp_fc_log2, phase) %>%
  dplyr::rename(symbol = preferred_symbol) %>%
  arrange(BH.Q)

save_rds_checked(display_dt, file = "results/shiny_data/mouse/xiphoid_cartilage/xiphoid_display_dt.rds")
```
